export const emojiOptions = [
  { value: "📝", label: "General Reference" },
  { value: "💻", label: "Programming Languages" },
  { value: "⚙️", label: "System Administration" },
  { value: "📁", label: "File System Operations" },
  { value: "🚀", label: "Deployment Processes" },
  { value: "🔧", label: "Developer Tools" },
  { value: "📊", label: "Data Science" },
  { value: "🗂️", label: "Database Management" },
  { value: "🔍", label: "Search Techniques" },
  { value: "🌐", label: "Networking Protocols" },
  { value: "🖥️", label: "Hardware Specifications" },
  { value: "🛠️", label: "Build and Automation" },
  { value: "🔒", label: "Security" },
  { value: "📱", label: "Mobile Development" },
  { value: "🎨", label: "Design and UI/UX" },
  { value: "🧪", label: "Testing and QA" },
  { value: "☁️", label: "Cloud Computing" },
  { value: "🤖", label: "Artificial Intelligence" },
  { value: "🔗", label: "Version Control" },
  { value: "📈", label: "Performance Optimization" },
  { value: "🌿", label: "Environment Setup" },
  { value: "🔌", label: "APIs and Integrations" },
  { value: "📦", label: "Package Management" },
  { value: "🏗️", label: "Architecture Patterns" },
];
